apiVersion: v1
kind: Service
metadata:
  name: example-stable
  namespace: canary-workload
  labels:
    app: example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: example
---
apiVersion: v1
kind: Service
metadata:
  name: example-canary
  namespace: canary-workload
  labels:
    app: example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: example
    role: canary  # This label is important for differentiating stable and canary pods
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example
  namespace: canary-workload
spec:
  hosts:
  - example.com
  gateways:
  - example-gateway
  http:
  - route:
    - destination:
        host: example-stable
        port:
          number: 80
      weight: 75
    - destination:
        host: example-canary
        port:
          number: 80
      weight: 25
