apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubesight
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: kubesight-cert
  dnsNames:
  - argocd.kubesight.online