applicationSet:
  replicas: 2
configs:
  params:
    server.insecure: true
controller:
  replicas: 1
redis-ha:
  enabled: true
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
server:
  autoscaling:
    enabled: true
    minReplicas: 2
