apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solar-ing
  namespace: solar-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: workload-nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: solar-system
                port:
                  number: 80
