apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solar-ing
  namespace: solar-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    route53.kubernetes.io/activate: "true"
    route53.kubernetes.io/domain-name: kubesidght.online
    route53.kubernetes.io/region: us-east-1
    route53.kubernetes.io/subdomain-name: sad-tenant

spec:
  ingressClassName: workload-nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: solar-system
                port:
                  number: 80
