apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ArulPrasath15/eks-infra.git'
    targetRevision: 'HEAD'
    path: cluster/charts/ingress-nginx
    helm:
      valueFiles:
        - cluster/charts/ingress-nginx/values.yaml 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  syncOptions:
    - CreateNamespace=true
